filecoin-project/system-test-matrix

.github/workflows/auto-merge.yml
=> feat: Add auto merge workflow

frontend/.eslintrc.js, frontend/apps/web/package.json, frontend/apps/web/scripts/data/convertAirtable.ts, frontend/apps/web/src/components/router/PublicRoute.tsx, frontend/apps/web/src/components/router/Router.tsx, frontend/apps/web/src/main.tsx, frontend/apps/web/src/model/index.ts, frontend/apps/web/src/pages/index.tsx, frontend/apps/web/src/types/RouteConfig.ts, frontend/apps/web/tsconfig.json, frontend/package.json, frontend/packages/build/package.json, frontend/packages/core/package.json, frontend/packages/ui/package.json, frontend/packages/ui/src/ButtonVariants.tsx, frontend/packages/ui/src/Icon.tsx, frontend/packages/ui/src/Layouts/PageLayout.tsx, frontend/packages/ui/src/Link.tsx, frontend/packages/ui/src/Table.tsx, frontend/packages/ui/src/stories/Link.stories.tsx, frontend/packages/ui/src/stories/Table.stories.tsx, frontend/yarn.lock
=> GitHub actions and libraries update

.github/workflows/deploy-fe.yml
=> fix: Missing working directory for deploy-fe

.github/workflows/deploy-storybook-on-demand.yml
=> fix: Missing working directory for storybook-on-demand

.github/workflows/deploy-fe.yml, frontend/apps/web/package.json
=> fix: S3 sync folder

frontend/apps/web/src/pages/index.tsx, frontend/apps/web/src/pages/tests.tsx, frontend/packages/core/src/i18n/translations/en.json
=> fix: Issues on tests page

frontend/apps/web/src/pages/behaviors.tsx
=> fix: Added button in behaviour's page header

frontend/packages/ui/src/Link.tsx, frontend/packages/ui/src/NativeLink.tsx, frontend/packages/ui/src/stories/Link.stories.tsx, frontend/packages/ui/src/stories/NativeLink.stories.tsx, frontend/test/__snapshots__/Storyshots.spec.ts.snap
=> feat: Updated NativeLink component

frontend/apps/web/src/pages/behaviors.tsx, frontend/apps/web/src/pages/tests.tsx, frontend/packages/ui/src/ProgressBar.tsx
Colors made fix for certain types of data in the Progress Bar
=> Progressbar-fixed-colors: Make colors fixed for certain types of data

frontend/apps/web/src/components/system/DetailedView.tsx, frontend/apps/web/src/components/system/Overview.tsx, frontend/apps/web/src/pages/index.tsx, frontend/apps/web/src/pages/system/_name.tsx, frontend/packages/ui/src/ProgressBar.tsx, frontend/packages/ui/src/Table.tsx, frontend/packages/ui/src/styles/colors.ts
=> feat: Polish the app

.github/workflows/auto-merge.yml
=> fix: Auto-merge is not working

frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/apps/web/src/pages/system/_name.tsx, frontend/packages/ui/src/Layouts/PageLayout.tsx, frontend/test/__snapshots__/Storyshots.spec.ts.snap
Button added in the header of the system/_name page
=> Breadcrumbs - just button

README.md, test-crawler/config.go, test-crawler/config.yaml, test-crawler/main.go
Updated readme and some minor fix
=> Small fixes

frontend/apps/web/scripts/data/systems/random/beacon.yml, frontend/apps/web/scripts/data/systems/random/drand.yml, frontend/apps/web/scripts/data/systems/random/rand.yml
Add yml files describing behaviors of beacon, Drand beacon, and rand subsystems.
Documentation change
=> Add beacon/rand behavior docs

frontend/apps/web/src/components/system/Overview.tsx, frontend/apps/web/src/pages/behaviors.tsx, frontend/apps/web/src/pages/tests.tsx, frontend/packages/core/src/utilities/mappers.ts
=> fix: Added more strict search and manual filter searching

frontend/apps/web/src/model/index.ts, frontend/apps/web/src/pages/behaviors.tsx, frontend/packages/core/src/i18n/translations/en.json, frontend/packages/types/src/behavior.ts
=> feat: Added system path column in behaviour table

.github/workflows/deploy-fe.yml
=> chore: Force cache

frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/packages/ui/src/Tooltip.tsx
=> chore: Fixed lint issue

frontend/packages/ui/src/ProgressBar.tsx
Fix colors for 'unparsed' and 'unannotated' tests
=> Modal refactor - Progress Bar colors fix

.github/workflows/deploy-fe.yml, frontend/apps/web/cypress.json, frontend/apps/web/cypress/.eslintrc.js, frontend/apps/web/cypress/fixtures/example.json, frontend/apps/web/cypress/integration/Homepage.spec.ts, frontend/apps/web/cypress/plugins/index.js, frontend/apps/web/cypress/support/commands.js, frontend/apps/web/cypress/support/index.d.ts, frontend/apps/web/cypress/support/index.js, frontend/apps/web/cypress/tsconfig.json, frontend/apps/web/package.json, frontend/apps/web/scripts/data/combineBehaviors.ts, frontend/apps/web/src/components/behaviors/BehaviorModal.tsx, frontend/apps/web/src/components/system/Overview.tsx, frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/apps/web/src/model/index.ts, frontend/apps/web/src/pages/behaviors.tsx, frontend/apps/web/src/pages/index.tsx, frontend/apps/web/src/pages/system/_system/_subsystem.tsx, frontend/apps/web/src/pages/tests.tsx, frontend/packages/types/src/testKindStatistic.ts, frontend/packages/types/src/testStatusStatistic.ts, frontend/packages/ui/src/TestLegend.tsx, frontend/packages/ui/src/Tooltip.tsx, frontend/tsconfig.json, frontend/yarn.lock
=> feat: Add cypress

frontend/README.md, frontend/apps/web/README.md, frontend/apps/web/scripts/data/README.md, frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/packages/ui/src/Layouts/PageLayoutFooter.tsx, frontend/packages/ui/src/Layouts/PageLayoutTab.tsx
=> fix: Readme,overall score,footer date,tab hover

frontend/.stylelintrc, frontend/packages/core/src/utilities/ui.ts, frontend/packages/ui/src/Dropdown/Dropdown.tsx, frontend/test/__snapshots__/Storyshots.spec.ts.snap
=> fix: Fixed dropdown when it opens upwards

frontend/apps/web/package.json
=> fix: Error when trying to serve app on windows machine

frontend/packages/ui/src/MatrixMap.tsx, frontend/packages/ui/src/TestLegend.tsx
=> fix: Changed matrix color

frontend/apps/web/src/components/system/MatrixTestKindsMapper.tsx
=> fix: Matrix status for kind fix

frontend/packages/ui/src/ProgressBar.tsx
=> fix: Fixed chaos test legend

frontend/apps/web/src/pages/index.tsx
=> fix: Removed links from progress bars on home page

frontend/apps/web/cypress/fixtures/constants.ts, frontend/apps/web/cypress/integration/AllBehaviours.ts, frontend/apps/web/cypress/integration/AllTests.ts, frontend/apps/web/cypress/integration/Homepage.spec.ts, frontend/apps/web/cypress/integration/Homepage.ts, frontend/apps/web/cypress/integration/Subsystem.ts, frontend/apps/web/cypress/integration/System.ts, frontend/apps/web/cypress/pages/allBehavioursPage.ts, frontend/apps/web/cypress/pages/allTestsPage.ts, frontend/apps/web/cypress/pages/homePage.ts, frontend/apps/web/cypress/pages/pageHeader.ts, frontend/apps/web/cypress/pages/subsystemPage.ts, frontend/apps/web/cypress/pages/systemPage.ts, frontend/apps/web/cypress/support/commands.js, frontend/apps/web/cypress/support/index.d.ts, frontend/apps/web/src/components/system/DetailedView.tsx, frontend/apps/web/src/pages/system/_system/_subsystem.tsx
=> feat: Refactored and merged all cypress test PR's to one

frontend/.eslintrc.js, frontend/packages/ui/src/Modal.tsx, frontend/packages/ui/src/__tests__/Modal.test.tsx, frontend/test/__snapshots__/Storyshots.spec.ts.snap
=> feat: Added unit test for modal component

frontend/packages/ui/src/ProgressBar.tsx, frontend/packages/ui/src/__tests__/ProgressBar.test.tsx
=> feat: Progress bar unit test

.github/workflows/deploy-test-crawler.yml, repo-to-crawl/uniqueREADME.md, test-crawler/.gitignore, test-crawler/config.yaml, test-crawler/test.md
=> feat: Added demo github action

frontend/apps/web/scripts/data/systems/cli/net.yaml, frontend/apps/web/scripts/data/systems/cli/wallet.yaml
=> add behaviors

frontend/apps/web/scripts/data/systems/cli/mempool.yml
=> Add mempool behaviors

frontend/README.md
=> chore: Added storybook link inside readme

frontend/packages/ui/src/Loader.tsx, frontend/packages/ui/src/__tests__/Loader.test.tsx, frontend/packages/ui/src/stories/loader/AllLoaderStories.stories.tsx, frontend/test/packages/ui/src/stories/loader/__snapshots__/AllLoaderStories.stories.storyshot, frontend/test/packages/ui/src/stories/loader/__snapshots__/Properties.stories.storyshot
=> feat: Added loader test and story

frontend/apps/web/src/components/behaviors/BehaviorModal.tsx, frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/apps/web/src/pages/tests.tsx
=> feat: Linked ciTests to tests statuses

.github/workflows/deploy-test-crawler.yml
=> feat: Trigger test crawler action update

frontend/apps/web/cypress/integration/AllBehaviours.ts, frontend/apps/web/cypress/integration/AllSystems.ts, frontend/apps/web/cypress/integration/AllTests.ts, frontend/apps/web/cypress/integration/Home.ts, frontend/apps/web/cypress/integration/Subsystem.ts, frontend/apps/web/cypress/integration/System.ts, frontend/apps/web/cypress/pages/allSystemsPage.ts, frontend/apps/web/cypress/pages/homePage.ts, frontend/apps/web/cypress/support/commands.js, frontend/apps/web/cypress/support/index.d.ts, frontend/apps/web/src/components/system/SystemHeader.tsx, frontend/apps/web/src/pages/index.tsx, frontend/apps/web/src/pages/system.tsx, frontend/packages/core/src/i18n/translations/en.json
=> feat: Created home and system pages

.github/workflows/deploy-ci-json.yml, .github/workflows/deploy-test-crawler.yml
=> feat: action that triggers generating of ci.json

README.md, frontend/apps/web/src/model/DenormalizedLoader.ts, frontend/apps/web/src/model/__tests__/helpers.ts, test-crawler/README.md
=> Documentation updates

frontend/packages/ui/src/ProgressBar.tsx
=> chore: added new color for cli bar

.github/workflows/deploy-ci-json.yml
=> fix: fixed ci deployment

.github/workflows/deploy-test-crawler.yml
=> chore: Changed link of lotus repo in git actions

.github/workflows/deploy-test-crawler.yml
=> chore: reverted lotus link in github action
